export {default as Login} from './Login/Login'
export {default as ResetPassRequest} from './ResetPassRequest/ResetPassRequest'
export {default as ResetPass} from './ResetPass/ResetPass'
export {default as ChangePass} from './ChangePass/ChangePass'
export {default as Register} from './Register/Register'
export {default as Verify} from './Verify/Verify'
